### ISSUE TITLE
Compatibile with Geocortex Essentials 4.6.3 and Geocortex Viewer for HTML5 2.7.2?

### ISSUE THREAD

**Issue by andrewbiggins** [DigitalDataServices/GeocortexMenuComponents#2]
Thanks for providing this custom component. Unfortunately I can't get it working with the latest version of Geocortex  (GE 4.6.3 and GVH 2.7.2).

I get the following error in the console when a HTML viewer loads: Error while including script ../MenuComponents.js: dojo.io.script error.

If you aren't able to fix this, would it be possible to provide the MenuComponents.js in an editable format so that I can try resolving the issue?

**Comment by andrewbiggins** [comment]
Never mind, I found a typo in the path to the script file, I've got it working now.

It would still be great to know if it is fully compatible with GE 4.6.3 and GVH 2.7.2.

**Comment by digitaldatasvcs** [comment]
Sorry for missing this. We have not tested with the latest versions due to time constraints.
